const matches=[{home:"Flamengo",away:"Palmeiras",hb:"🔴",ab:"🟢",time:"16:00",odds:[1.85,3.4,4.1]},{home:"Santos",away:"Grêmio",hb:"⚪",ab:"🔵",time:"18:30",odds:[2.1,3.2,2.8]},{home:"Corinthians",away:"São Paulo",hb:"⚫",ab:"⚪",time:"21:00",odds:[2.35,3.1,2.65]},{home:"Bahia",away:"Cruzeiro",hb:"🔵",ab:"🔷",time:"19:00",odds:[2.25,3.15,2.9]},{home:"Fluminense",away:"Botafogo",hb:"🟢",ab:"⚫",time:"20:30",odds:[2.05,3.3,3.05]},{home:"Atlético-MG",away:"Internacional",hb:"⚫",ab:"🔴",time:"21:00",odds:[1.95,3.35,3.55]}];
let current=0,balance=100,score=0,history=[],selected=null,notes=JSON.parse(localStorage.getItem("brbet_notes")||"[]");const $=id=>document.getElementById(id);
function probs(m){const raw=m.odds.map(o=>1/o),sum=raw.reduce((a,b)=>a+b,0);return raw.map(x=>Math.round(x/sum*100))}
function renderMatch(){const m=matches[current],p=probs(m);$("roundNumber").textContent=current+1;$("matchRound").textContent=current+1;$("matchNumber").textContent="JOGO "+String(current+1).padStart(2,"0");$("progressBar").style.width=((current+1)/matches.length*100)+"%";$("matchTime").textContent="Hoje • "+m.time;$("matchClock").textContent=m.time;$("homeTeam").textContent=m.home;$("awayTeam").textContent=m.away;$("homeChoice").textContent=m.home;$("awayChoice").textContent=m.away;$("homeBadge").textContent=m.hb;$("awayBadge").textContent=m.ab;["home","draw","away"].forEach((x,i)=>{$(x+"Odd").textContent=m.odds[i].toFixed(2);$(x+"Chance").textContent="Chance "+p[i]+"%";$(x+"ChanceBar").style.width=p[i]+"%"});selected=null;document.querySelectorAll(".choice").forEach(b=>b.classList.remove("selected"));updateBet()}
function updateBalance(){$("balance").textContent="R$ "+balance.toFixed(2).replace(".",",");$("heroBalance").textContent=balance.toFixed(2).replace(".",",");$("miniBalance").textContent="R$ "+balance.toFixed(2).replace(".",",")}
function updateBet(){const stake=Math.min(Math.max(Number($("stake").value)||0,0),balance),m=matches[current];$("stake").max=balance;const idx=selected==="home"?0:selected==="draw"?1:2;$("potentialReturn").textContent="R$ "+(selected?stake*m.odds[idx]:0).toFixed(2).replace(".",",");$("potentialProfit").textContent="Lucro possível: R$ "+Math.max(0,(selected?stake*m.odds[idx]:0)-stake).toFixed(2).replace(".",",");const btn=$("confirmButton");if(!selected){$("selectionInfo").className="selection-info";$("selectionInfo").textContent="Selecione uma opção acima para ver a chance estimada de ganhar e perder.";btn.disabled=true;btn.textContent="ESCOLHA UM RESULTADO";return}const p=probs(m);$("selectionInfo").className="selection-info active";$("selectionInfo").innerHTML='Chance estimada de ganhar: <span class="win">'+p[idx]+'%</span> • chance estimada de perder: <span class="lose">'+(100-p[idx])+'%</span>';btn.disabled=stake<1;btn.textContent=stake<1?"VALOR INVÁLIDO":"CONFIRMAR PALPITE • R$ "+stake.toFixed(2).replace(".",",")}
function addNote(title,msg){notes.unshift({title,msg});notes=notes.slice(0,8);localStorage.setItem("brbet_notes",JSON.stringify(notes));renderNotes();toast(title,msg)}
function renderNotes(){$("notificationCount").textContent=notes.length;$("notificationCount").classList.toggle("show",notes.length>0);$("notificationsList").innerHTML=notes.length?notes.map(n=>'<div class="notification"><strong>'+safe(n.title)+'</strong><p>'+safe(n.msg)+'</p></div>').join(""):"<div class='notification'>Tudo certo por aqui.</div>"}
function safe(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(title,msg){const t=document.createElement("div");t.className="toast";t.innerHTML="<strong>"+safe(title)+"</strong><p>"+safe(msg)+"</p>";$("toastContainer").appendChild(t);setTimeout(()=>t.remove(),2800)}
function renderHistory(){if(!history.length){$("history").className="history-empty";$("history").textContent="Você ainda não fez nenhum palpite.";return}$("history").className="history-list";$("history").innerHTML=history.map((h,i)=>'<div class="history-item"><span>Jogo '+(i+1)+': '+safe(h.game)+' • R$ '+h.stake.toFixed(2).replace(".",",")+'</span><b>'+safe(h.pick)+'</b></div>').join("")}
function makePick(){const m=matches[current],stake=Math.min(Math.max(Number($("stake").value)||0,0),balance);if(!selected||stake<1)return;const i=selected==="home"?0:selected==="draw"?1:2,p=probs(m),pick=selected==="home"?m.home:selected==="away"?m.away:"Empate",odd=m.odds[i];balance-=stake;score++;history.push({game:m.home+" x "+m.away,pick:pick+" • "+odd.toFixed(2)+" • chance "+p[i]+"%",stake});$("score").textContent=score;updateBalance();renderHistory();addNote("Palpite confirmado",m.home+" x "+m.away+" → "+pick+" • R$ "+stake.toFixed(2));current=(current+1)%matches.length;setTimeout(()=>{renderMatch();window.scrollTo({top:$("palpite").offsetTop-80,behavior:"smooth"});toast("Próximo jogo",matches[current].home+" x "+matches[current].away)},350)}
document.addEventListener("DOMContentLoaded",()=>{renderMatch();renderHistory();renderNotes();updateBalance();document.querySelectorAll(".choice").forEach(b=>b.addEventListener("click",()=>{selected=b.dataset.pick;document.querySelectorAll(".choice").forEach(x=>x.classList.toggle("selected",x===b));updateBet()}));$("stake").addEventListener("input",updateBet);document.querySelectorAll("[data-stake]").forEach(b=>b.addEventListener("click",()=>{$("stake").value=Math.min(Number(b.dataset.stake),balance);updateBet()}));$("confirmButton").addEventListener("click",makePick);$("notificationButton").addEventListener("click",e=>{$("notificationPanel").classList.toggle("open");e.stopPropagation()});$("clearNotifications").addEventListener("click",()=>{notes=[];localStorage.removeItem("brbet_notes");renderNotes()});document.addEventListener("click",e=>{if(!e.target.closest(".notifications")&&!e.target.closest("#notificationButton"))$("notificationPanel").classList.remove("open")})});