const teams=[
  {name:"Flamengo",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Flamengo_braz_logo.svg"},
  {name:"Palmeiras",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Palmeiras_logo.svg"},
  {name:"Corinthians",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Corinthians_simbolo.svg"},
  {name:"São Paulo",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Sao_Paulo_FC_crest.svg"},
  {name:"Santos",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Santos_logo.svg"},
  {name:"Grêmio",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Gremio_logo.svg"},
  {name:"Internacional",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/SC_Internacional_Brazil_logo.svg"},
  {name:"Bahia",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/ECBahia.svg"},
  {name:"Cruzeiro",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Cruzeiro_Esporte_Clube_(logo).svg"},
  {name:"Fluminense",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Fluminense_FC_escudo.svg"},
  {name:"Botafogo",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Botafogo_de_Futebol_e_Regatas_logo.svg"},
  {name:"Vasco",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/CR_Vasco_da_Gama_logo.svg"},
  {name:"Atlético-MG",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Clube_Atl%C3%A9tico_Mineiro_logo.svg"},
  {name:"Athletico-PR",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Club_Athletico_Paranaense.svg"},
  {name:"Fortaleza",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Fortaleza_EC_2021_logo.svg"},
  {name:"Ceará",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Cear%C3%A1_Sporting_Club_logo.svg"},
  {name:"Sport",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Sport_Club_do_Recife_logo.svg"},
  {name:"Vitória",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Esporte_Clube_Vit%C3%B3ria.svg"},
  {name:"Bragantino",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Red_Bull_Bragantino_logo.svg"},
  {name:"Juventude",badge:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Esporte_Clube_Juventude.svg"}
];
const games=[
  ["Flamengo","Palmeiras","16:00",[1.85,3.4,4.1]],["Corinthians","São Paulo","18:30",[2.35,3.1,2.65]],["Santos","Grêmio","21:00",[2.1,3.2,2.8]],["Bahia","Cruzeiro","19:00",[2.25,3.15,2.9]],["Fluminense","Botafogo","20:30",[2.05,3.3,3.05]],["Vasco","Atlético-MG","16:00",[2.7,3.2,2.25]],["Athletico-PR","Fortaleza","18:00",[2.0,3.25,3.4]],["Ceará","Sport","20:00",[2.15,3.1,3.1]],["Vitória","Bragantino","17:30",[2.8,3.25,2.2]],["Juventude","Internacional","21:30",[3.15,3.15,2.05]]
].map(([h,a,time,odds])=>({home:h,away:a,time,odds,hb:teams.find(t=>t.name===h)?.badge,ab:teams.find(t=>t.name===a)?.badge}));
let n=0,balance=100,selected=null,hist=[],notes=[];
const $=x=>document.getElementById(x),money=x=>"R$ "+Number(x).toFixed(2).replace(".",",");
function p(g){let a=g.odds.map(x=>1/x),s=a.reduce((x,y)=>x+y,0);return a.map(x=>Math.round(x/s*100))}
function badgeHTML(url,name){return url?"<img src='"+url+"' alt='Escudo do "+safe(name)+"' loading='lazy' onerror=\"this.style.display='none';this.parentElement.textContent='⚽'\">":"⚽"}
function balanceUI(){$("balance").textContent=money(balance);$("miniBalance").textContent=money(balance);$("heroBalance").textContent=balance.toFixed(2).replace(".",",")}
function render(){let g=games[n],q=p(g);$("roundNumber").textContent=n+1;$("matchRound").textContent=n+1;$("matchNumber").textContent="JOGO "+String(n+1).padStart(2,"0");$("progressBar").style.width=((n+1)/games.length*100)+"%";$("matchTime").textContent="Hoje • "+g.time;$("matchClock").textContent=g.time;$("homeTeam").textContent=g.home;$("awayTeam").textContent=g.away;$("homeChoice").textContent=g.home;$("awayChoice").textContent=g.away;$("homeBadge").innerHTML=badgeHTML(g.hb,g.home);$("awayBadge").innerHTML=badgeHTML(g.ab,g.away);["home","draw","away"].forEach((x,i)=>{$(x+"Odd").textContent=g.odds[i].toFixed(2);$(x+"Chance").textContent=q[i]+"%";$(x+"ChanceBar").style.width=q[i]+"%"});selected=null;document.querySelectorAll(".choice").forEach(x=>{x.classList.remove("selected");x.disabled=false});$("stake").max=balance;$("stake").value=Math.min(10,Math.max(1,balance));balanceUI();betUI()}
function betUI(){let v=Math.min(Math.max(Number($("stake").value)||0,0),balance),g=games[n],i=selected==="home"?0:selected==="draw"?1:2,r=selected?v*g.odds[i]:0;$("potentialReturn").textContent=money(r);$("potentialProfit").textContent=selected?"Lucro possível: "+money(Math.max(0,r-v)):"Selecione um resultado";let b=$("confirmButton");if(!selected){$("selectionInfo").className="info";$("selectionInfo").textContent="Escolha Casa, Empate ou Fora para continuar.";b.disabled=true;b.textContent="ESCOLHA UM RESULTADO →";return}let q=p(g);$("selectionInfo").className="info active";$("selectionInfo").innerHTML="Chance de ganhar: <span class='win'>"+q[i]+"%</span> • chance de perder: <span class='lose'>"+(100-q[i])+"%</span>";b.disabled=v<1||v>balance;b.textContent="CONFIRMAR PALPITE →"}
function safe(x){return String(x).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}
function toast(t,m){let x=document.createElement("div");x.className="toast";x.innerHTML="<b>"+safe(t)+"</b><p>"+safe(m)+"</p>";$("toastContainer").appendChild(x);setTimeout(()=>x.remove(),2600)}
function historyUI(){if(!hist.length){$("history").textContent="Nenhum palpite realizado ainda.";return}$("history").className="history-list";$("history").innerHTML=hist.map((x,i)=>"<div class='history-item'><span>Jogo "+(i+1)+" • "+safe(x.game)+" • "+money(x.stake)+"</span><b class='"+(x.win?"history-win":"history-loss")+"'>"+x.status+"</b></div>").join("")}
function note(t,m){notes.unshift({t,m});$("notificationCount").textContent=notes.length;$("notificationCount").classList.add("show");$("notificationsList").innerHTML=notes.map(x=>"<div class='notification'><b>"+safe(x.t)+"</b><p>"+safe(x.m)+"</p></div>").join("");toast(t,m)}
function result(g,pick,actual,stake,odd,win){let x=document.createElement("div");x.className="result-overlay";x.innerHTML="<div class='result-card "+(win?"result-win":"result-loss")+"'><div class='result-icon'>"+(win?"✓":"×")+"</div><h2>"+(win?"VOCÊ GANHOU!":"VOCÊ PERDEU")+"</h2><p class='result-game'>"+safe(g.home+" x "+g.away)+"</p><div class='result-lines'><div><span>Seu palpite</span><b>"+safe(pick)+"</b></div><div><span>Resultado</span><b>"+safe(actual)+"</b></div><div><span>Valor</span><b>"+money(stake)+"</b></div><div><span>"+(win?"Retorno":"Perda")+"</span><b class='"+(win?"positive":"negative")+"'>"+(win?"+ "+money(stake*odd):"- "+money(stake))+"</b></div></div><button id='nextGameButton'>PRÓXIMO JOGO →</button></div>";document.body.appendChild(x);$("nextGameButton").onclick=()=>{x.remove();n=(n+1)%games.length;render();document.getElementById("palpite").scrollIntoView({behavior:"smooth"})}}
function place(){let g=games[n],stake=Math.min(Math.max(Number($("stake").value)||0,0),balance);if(!selected||stake<1||stake>balance)return;let i=selected==="home"?0:selected==="draw"?1:2,q=p(g),pick=i===0?g.home:i===1?"Empate":g.away,odd=g.odds[i],r=Math.random()*100,t=0,ri=0;for(let k=0;k<q.length;k++){t+=q[k];if(r<t){ri=k;break}}let actual=ri===0?g.home:ri===1?"Empate":g.away,win=ri===i;balance-=stake;if(win)balance+=stake*odd;hist.push({game:g.home+" x "+g.away,stake,win,status:win?"GANHOU":"PERDEU"});balanceUI();historyUI();note(win?"Você ganhou!":"Você perdeu",g.home+" x "+g.away+" • "+actual);document.querySelectorAll(".choice").forEach(x=>x.disabled=true);setTimeout(()=>result(g,pick,actual,stake,odd,win),200)}
document.addEventListener("DOMContentLoaded",()=>{render();historyUI();document.querySelectorAll(".choice").forEach(x=>x.onclick=()=>{selected=x.dataset.pick;document.querySelectorAll(".choice").forEach(y=>y.classList.toggle("selected",y===x));betUI()});$("stake").oninput=betUI;document.querySelectorAll("[data-stake]").forEach(x=>x.onclick=()=>{$("stake").value=Math.min(+x.dataset.stake,balance);betUI()});$("confirmButton").onclick=place;$("notificationButton").onclick=e=>{$("notificationPanel").classList.toggle("open");e.stopPropagation()};$("clearNotifications").onclick=()=>{$("notificationCount").classList.remove("show");notes=[];$("notificationsList").innerHTML=""}});
